branches:
  only:
  - java11
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS-BigSur

for:
-
  matrix:
    only:
      - image: macOS-BigSur
  init:
  - sh: >-
      brew install maven
      
      brew install openjdk@11
      
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

  environment:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
  cache: $HOME/.m2
  build_script:
  - sh: >-
      /usr/libexec/java_home -V
      
      export JAVA_HOME=`/usr/libexec/java_home -v 11`
      
      mvn -v
      
      mvn -B -DskipTests clean package

-
  matrix:
    only:
      - image: Ubuntu2004
  stack: jdk 11
  init:
  - sh: >-
      sudo rm /usr/lib/jvm/java-11-openjdk-amd64/java-11-openjdk-amd64
  cache: $HOME/.m2
  build_script:
  - sh: >-
      export PATH=${JAVA_HOME_11_X64}/bin:$PATH
      
      unset JAVA_HOME
      
      mvn -v
      
      mvn -B -DskipTests clean package

-
  matrix:
    only:
      - image: Visual Studio 2019
  cache:
    - "%USERPROFILE%\\.m2"
  init:
    - ps: iwr -useb get.scoop.sh | iex
    - cmd: |
        scoop bucket add extras
        scoop install inno-setup
        scoop install wixtoolset
  build_script:
    - cmd: |
        set
        path C:\Program Files\Java\jdk11\bin;%PATH%
        java -version
        set JAVA_HOME=C:\Progra~1\Java\jdk11
        mvn -v
        mvn -B -DskipTests clean package
