branches:
  only:
  - java11
image:
  - Ubuntu2004
  - macOS-BigSur

for:
-
  matrix:
    only:
      - image: macOS-BigSur
  init:
  - sh: >-
      brew install maven
      
      brew install openjdk@11
      
      sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk

  environment:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
  cache: $HOME/.m2
  build_script:
  - sh: >-
      /usr/libexec/java_home -V
      
      export JAVA_HOME=`/usr/libexec/java_home -v 11`
      
      mvn -v
      
      mvn -B -DskipTests clean package

-
  matrix:
    only:
      - image: Ubuntu2004
  stack: jdk 11
  init:
  - sh: >-
      update-java-alternatives -l || echo
  cache: $HOME/.m2
  build_script:
  - sh: >-
      java -version
      
      export PATH=/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin:$PATH
      
      java -version
      
      ls -lR /usr/lib/jvm/java-1.11.0-openjdk-amd64
      
      echo $JAVA_HOME
      
      unset JAVA_HOME
      
      mvn -v
      
      mvn -B -DskipTests clean package