
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"

jobs:
  include:
    - os: linux
      dist: trusty
      language: java
      jdk:
        - oraclejdk8
    - os: osx
      osx_image: xcode9.3
      language: java
      jdk:
        - oraclejdk8
    - os: windows
      language: shell
      before_install:
        - choco install jdk8 -params 'installdir=c:\\jdk8'
        - export PATH=$PATH:"/c/jdk8/bin"
        - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
        - source $GRAVIS/install-maven

#deploy:
#  provider: releases
#  api_key:
#    secure: LiA9uMg3JgtpLioXFf5CAwhtTsjGoBLkgIq4p1KCPL7EaD+16zeux+NDHqc48vMARZR3dHIoJlprwHWcLyq70Lls42KucqEJBA5tBE2WwOJvO2C82d1MnkQVFs7L3FDBIOSXO7Eid8IRn/Wg7DZVmePLGrmQIEStVMC+BZqI9Uh9tN3lqwiNXlaMd89Q67wNELWfy4n1znfZXn0u43HtEZ1ls0NLPJloUedXuVkVOEpxJrsRK1fW4jpAkdGZr5pesOzP4vK0Y1G6uA+uDD3qFzYY+8x67fZDGoHfZEzeBi85YvbSGI4grL9HMLcsdk+NrkB/UyaOwGbBWVa9zCR8a2UWMSFAijTNydA9YlAWrggLycXQbXoH6nyEzxHNju4RTpmNDDHsiUEssq/+ajblLSiYH7ln/4GIXNSVkXWYd4NNgBW2pUU3MxBOq93TqCQjttzPYmANwYAdJF7JodZfAAXACVQr2oNtMdSshVAHyNCRLIaeyFmz/uvmtgX7CUQfUh+fWKfvUMW8BVSQwj5iAe4egT3IqbDVYH7a5bpiIJLZbbHNSKrkRs2mMe6BL4rj0j9cAuBO2Tden6lXlsyh7u1xtDjNMlrAhkfeAgZZxIG+wuy4PwQbjP+sxpmdZilMEeYCO9eTBQ1v4mV9wqNRDBrCnnmJxBcYMZqfvLs/Ysw=
#  skip_cleanup: true
#  file_glob: true
#  file:
#    - dist/target/back2back-dist-*.tar.gz
#    - dist/target/back2back-dist-*.zip
#    - dist/target/back2back-setup.exe
#  overwrite: true
#  on:
#    tags: true
