# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-linux:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - run:
          name: Install Maven
          command: |
            apt-get update
            apt-get -y install unzip
            wget --no-check-certificate https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip
            unzip apache-maven-3.8.4-bin.zip
      - run:
          name: Build
          command: |
            alias mvn=apache-maven-3.8.4/bin/mvn            
            mvn -v
            mvn -B -DskipTests clean package

  build-mac:
    macos:
      xcode: 11.5.0
    steps:
      - run:
          name: Install Maven
          command: brew install maven
      - checkout
      - run:
          name: Build
          command: |
            /usr/libexec/java_home -V
            export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
            mvn -v
            mvn -B -DskipTests clean package

  build-windows:
    executor:
      name: win/default
    steps:
      - run:
          name: Install Oracle JDK8
          shell: powershell.exe
          command: choco install jdk8 -params 'installdir=c:\\jdk8'
      - run:
          name: Install scoop
          shell: powershell.exe
          command: iwr -useb get.scoop.sh | iex
      - run:
          name: Install dependencies
          shell: powershell.exe
          command: |
            scoop bucket add extras
            scoop install maven
            scoop install inno-setup
            scoop install wixtoolset
      - checkout
      - run:
          name: Build
          command: |
            mvn -v
            mvn -B -DskipTests clean package

workflows:
  default:
    jobs:
      - build-linux
#      - build-mac
      - build-windows
