# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  build-mac:
    macos:
      xcode: 13.2.1
    steps:
      - checkout
      - run:
          name: Install scoop
          shell: powershell.exe
          command: iwr -useb get.scoop.sh | iex
      - run:
          name: Install JDK, Maven
          shell: powershell.exe
          command: |
            scoop bucket add java
            scoop install openjdk11
            scoop install maven
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

  build-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

workflows:
  default:
    jobs:
      - build-linux
      - build-mac
      - build-windows
