# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build-linux:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mvn -v
            mvn -B -DskipTests clean package
      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/artifacts
            cd xpman-fx-dist/target
            cp *.deb *.rpm /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: linux

  build-mac:
    macos:
      xcode: 13.3.0
    steps:
      - run:
          name: Fix Finder got an error - AppleEvent timed out. (-1712)
          command: |
            epochdate=$(($(date +'%s * 1000 + %-N / 1000000')))
            tcc_service_appleevents="replace into access (service,client,client_type,auth_value,auth_reason,auth_version,indirect_object_identifier_type,indirect_object_identifier,flags,last_modified) values (\"kTCCServiceAppleEvents\",\"/usr/sbin/sshd\",1,2,4,1,0,\"com.apple.finder\",0,$epochdate);"
            sudo sqlite3 "/Users/distiller/Library/Application Support/com.apple.TCC/TCC.db" "$tcc_service_appleevents"
      - run:
          name: Install Maven
          command: brew install maven
      - checkout
      - run:
          name: Build
          command: |
            /usr/libexec/java_home -V
            export JAVA_HOME=`/usr/libexec/java_home -v 11`
            mvn -v
            mvn -B -DskipTests clean package
      - run:
          name: Prepare artifacts
          command: |
            mkdir /tmp/artifacts
            cd xpman-fx-dist/target
            cp *.dmg *.pkg /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: mac

  build-windows:
    executor:
      name: win/default
    steps:
      - run:
          name: Install scoop
          shell: powershell.exe
          command: iwr -useb get.scoop.sh | iex
      - run:
          name: Install dependencies
          shell: powershell.exe
          command: |
            scoop bucket add java
            scoop bucket add extras
            scoop install openjdk11
            scoop install maven
            scoop install inno-setup
            scoop install wixtoolset
      - checkout
      - run:
          name: Build
          command: |
            mvn -v
            mvn -B -DskipTests clean package
      - run:
          name: Prepare artifacts
          command: |
            mkdir .\artifacts
            cp xpman-fx-dist\target\*.exe .\artifacts
            cp xpman-fx-dist\target\*.msi .\artifacts
      - store_artifacts:
          path: .\artifacts
          destination: windows

workflows:
  default:
    jobs:
      - build-linux
      - build-mac
      - build-windows
