module xpman.fx {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires lombok;
    requires xpman.api;
    requires org.slf4j;
    requires com.google.gson;
    requires org.controlsfx.controls;
    requires spring.expression;
    requires commons.lang;
    requires ch.qos.logback.classic;
    requires com.sun.jna;
    requires com.sun.jna.platform;
    requires java.desktop;

    exports com.ogerardin.xpman.panels.aircrafts;
    exports com.ogerardin.xpman.tools;
    exports com.ogerardin.xpman.util.jfx.console;
    exports com.ogerardin.xpman;
    exports com.ogerardin.xpman.util;
    exports com.ogerardin.xpman.util.jfx;
    exports com.ogerardin.xpman.panels;
    exports com.ogerardin.xpman.util.jfx.cell_factory;
    exports com.ogerardin.xpman.util.jfx.row_factory;

    opens com.ogerardin.xpman to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.config to com.google.gson;
    opens com.ogerardin.xpman.diag to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.install.wizard to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.panels.about to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.panels.aircrafts to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.aircrafts.details to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.navdata to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.plugins to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.scenery to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.scenery.rules to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.scenery.wizard to javafx.base, javafx.fxml, spring.expression;
    opens com.ogerardin.xpman.panels.xplane to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.scenery_organizer to javafx.base, javafx.fxml, spring.expression, com.google.gson;
    opens com.ogerardin.xpman.tools to javafx.fxml, javafx.base;
    opens com.ogerardin.xpman.util.jfx to javafx.base, javafx.fxml, com.google.gson;
    opens com.ogerardin.xpman.util.jfx.console to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.util.jfx.menu to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.util.jfx.menu.annotation to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.util.jfx.wizard to javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.util.jfx.cell_factory to com.google.gson, javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.util.jfx.row_factory to com.google.gson, javafx.base, javafx.fxml;
    opens com.ogerardin.xpman.panels.xplane.breakdown to javafx.base, javafx.fxml;
}